# Generated by Django 4.0.5 on 2022-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_loc', models.CharField(max_length=50, verbose_name='Название')),
                ('type_loc', models.CharField(max_length=50, verbose_name='Тип')),
                ('function_loc', models.CharField(max_length=50, verbose_name='Назначение')),
                ('year', models.CharField(max_length=50, verbose_name='Год выпуска')),
                ('country_loc', models.CharField(max_length=50, verbose_name='Страна изготовитель')),
                ('construction_speed', models.CharField(max_length=50, verbose_name='Конструкционная скорость')),
                ('weight_loc', models.CharField(max_length=50, verbose_name='Масса')),
                ('length_loc', models.CharField(max_length=50, verbose_name='Длина')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локомотив',
                'verbose_name_plural': 'Локомотивы',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
