# Generated by Django 4.0.5 on 2022-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_locomotive_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotive',
            name='construction_speed',
            field=models.IntegerField(max_length=50, verbose_name='Конструкционная скорость'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='length_loc',
            field=models.IntegerField(max_length=50, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='weight_loc',
            field=models.IntegerField(max_length=50, verbose_name='Масса'),
        ),
    ]
