# Generated by Django 4.0.5 on 2022-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_locomotive_construction_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotive',
            name='construction_speed',
            field=models.IntegerField(max_length=50, verbose_name='Конструкционная скорость, км/ч:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='country_loc',
            field=models.CharField(max_length=50, verbose_name='Страна изготовитель:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='description',
            field=models.TextField(verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='function_loc',
            field=models.CharField(max_length=50, verbose_name='Назначение:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='length_loc',
            field=models.IntegerField(max_length=50, verbose_name='Длина, мм:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='name_loc',
            field=models.CharField(max_length=50, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='type_loc',
            field=models.CharField(max_length=50, verbose_name='Тип:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='weight_loc',
            field=models.IntegerField(max_length=50, verbose_name='Масса, т:'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска, год:'),
        ),
    ]
